const Dom = [
    {
        id: 1,
        photo: "img/card-img-5.jpg",
        duration: '5 days, 4 nights',
        price: '29,999',
        name: "Discover Kerala aka the God's Own Country",
        planeicon: "fa-solid fa-plane",
        planestat: '3 Flights',
        hotelicon: "fa-solid fa-building",
        hotelstat: '3 Hotels',
        personicon: "fa-solid fa-person-walking",
        personstat: '5 Activities',
        caricon: "fa-solid fa-car",
        carstat: "1 Transfer",
        category: "Family Pack",
        living: 'Kerala, India',
        going:"/kerala"
    },
        
    {
        id: 1,
        photo: "img/card-img-7.jpg",
        duration: '6 days, 5 nights',
        price: '37,826',
        name: 'Experience island life of Andaman',
        planeicon: "fa-solid fa-plane",
        planestat: '3 Flights',
        hotelicon: "fa-solid fa-building",
        hotelstat: '3 Hotels',
        personicon: "fa-solid fa-person-walking",
        personstat: '11 Activities',
        caricon: "fa-solid fa-car",
        carstat: "1 Transfer",
        category: "Adventure Pack",
        living: 'Andaman, India',
        going:"/andaman"
    },
        
    {
        id: 1,
        photo: "img/card-img-8.jpg",
        duration: '3 days, 2 nights',
        price: '19,629',
        name: 'Explore Hyderabad aka the City of Pearls',
        planeicon: "fa-solid fa-plane",
        planestat: '2 Flights',
        hotelicon: "fa-solid fa-building",
        hotelstat: '1 Hotel',
        personicon: "fa-solid fa-person-walking",
        personstat: '0 Activity',
        caricon: "fa-solid fa-car",
        carstat: "0 Transfer",
        category: "Family Pack",
        living: 'Hyderabad, India',
        going:"/hyderabad"
    },
        
    {
        id: 1,
        photo: "img/card-img-1.jpg",
        duration: '6 days, 5 nights',
        price: '62,000',
        name: 'Discover breathtaking landscapes of Ladakh',
        planeicon: "fa-solid fa-plane",
        planestat: '3 Flights',
        hotelicon: "fa-solid fa-building",
        hotelstat: '2 Hotels',
        personicon: "fa-solid fa-person-walking",
        personstat: '5 Activities',
        caricon: "fa-solid fa-car",
        carstat: "1 Transfer",
        category: "Adventure Pack",
        living: 'Ladakh, India',
        going:"/ladakh"
    },
        
    {
        id: 1,
        photo: "img/card-img-2.jpg",
        duration: '5 days, 4 nights',
        price: '35,000',
        name: "Weekend gateway to Goa",
        planeicon: "fa-solid fa-plane",
        planestat: '7 Flights',
        hotelicon: "fa-solid fa-building",
        hotelstat: '1 Hotel',
        personicon: "fa-solid fa-person-walking",
        personstat: '4 Activities',
        caricon: "fa-solid fa-car",
        carstat: "0 Transfer",
        category: "Solo Pack",
        living: 'Goa, India',
        going:"/goa"
    },
        
    {
        id: 1,
        photo: "img/guwahati.jpg",
        duration: '4 days, 3 nights',
        price: '33,860',
        name: "Experience the Cultures of Guwahati",
        planeicon: "fa-solid fa-plane",
        planestat: '4 Flights',
        hotelicon: "fa-solid fa-building",
        hotelstat: '2 Hotels',
        personicon: "fa-solid fa-person-walking",
        personstat: '4 Activities',
        caricon: "fa-solid fa-car",
        carstat: "1 Transfer",
        category: "Family Pack",
        living: 'Assam, India',
        going:"/guwahati"
    },
        
    {
        id: 1,
        photo: "img/shimla.jpg",
        duration: '6 days, 5 nights',
        price: '26,134',
        name: "Travel to Shimla, The Queen of Hills",
        planeicon: "fa-solid fa-plane-slash",
        planestat: '0 Flight',
        hotelicon: "fa-solid fa-building",
        hotelstat: '2 Hotels',
        personicon: "fa-solid fa-person-walking",
        personstat: '5 Activities',
        caricon: "fa-solid fa-car",
        carstat: "3 Transfers",
        category: "Adventure Pack",
        living: 'Himachal Pradesh, India',
        going:"/shimla"
    },
        
    {
        id: 1,
        photo: "img/rajasthan.jpg",
        duration: '4 days, 3 nights',
        price: '32,812',
        name: "Explore the History Behind Rajasthan",
        planeicon: "fa-solid fa-plane",
        planestat: '2 Flights',
        hotelicon: "fa-solid fa-building",
        hotelstat: '1 Hotel',
        personicon: "fa-solid fa-person-walking",
        personstat: '5 Activities',
        caricon: "fa-solid fa-car",
        carstat: "2 Transfers",
        category: "Couples Pack",
        living: 'Rajasthan, India',
        going:"/rajasthan"
    },
        
    {
        id: 1,
        photo: "img/sikkim.jpg",
        duration: '5 days, 4 nights',
        price: '32,688',
        name: "Adventure the Mountains of Sikkim",
        planeicon: "fa-solid fa-plane",
        planestat: '3 Flights',
        hotelicon: "fa-solid fa-building",
        hotelstat: '2 Hotels',
        personicon: "fa-solid fa-person-walking",
        personstat: '6 Activities',
        caricon: "fa-solid fa-car",
        carstat: "3 Transfers",
        category: "Solo Pack",
        living: 'Sikkim, India',
        going:"/sikkim"
    },
        
    {
        id: 1,
        photo: "img/punjab.jpg",
        duration: '7 days, 6 nights',
        price: '23,323',
        name: "Visit Punjab, The Land of Five Rivers",
        planeicon: "fa-solid fa-plane-slash",
        planestat: '0 Flight',
        hotelicon: "fa-solid fa-building",
        hotelstat: '3 Hotels',
        personicon: "fa-solid fa-person-walking",
        personstat: '5 Activities',
        caricon: "fa-solid fa-car",
        carstat: "3 Transfers",
        category: "Family Pack",
        living: 'Punjab, India',
        going:"/punjab"
    },
        
    {
        id: 1,
        photo: "img/himachal.jpg",
        duration: '8 days, 7 nights',
        price: '15,657',
        name: "Experience the Beauty of The Himachal",
        planeicon: "fa-solid fa-plane-slash",
        planestat: '0 Flight',
        hotelicon: "fa-solid fa-building",
        hotelstat: '3 Hotels',
        personicon: "fa-solid fa-person-walking",
        personstat: '6 Activities',
        caricon: "fa-solid fa-car",
        carstat: "4 Transfers",
        category: "Adventure Pack",
        living: 'Himachal Pradesh, India',
        going:"/himachalpradesh"
    },
        
    {
        id: 1,
        photo: "img/darjeeling.jpg",
        duration: '4 days, 3 nights',
        price: '23,392',
        name: "Wander the Lands of Darjeeling",
        planeicon: "fa-solid fa-plane-slash",
        planestat: '0 Flight',
        hotelicon: "fa-solid fa-building",
        hotelstat: '2 Hotels',
        personicon: "fa-solid fa-person-walking",
        personstat: '4 Activities',
        caricon: "fa-solid fa-car",
        carstat: "4 Transfers",
        category: "Couples Pack",
        living: 'West Bengal, India',
        going:"/darjeeling"
    },
        
    {
        id: 1,
        photo: "img/bangalore.jpg",
        duration: '5 days, 4 nights',
        price: '26,534',
        name: "Visit The Silicon Valley of India",
        planeicon: "fa-solid fa-plane",
        planestat: '3 Flights',
        hotelicon: "fa-solid fa-building",
        hotelstat: '3 Hotels',
        personicon: "fa-solid fa-person-walking",
        personstat: '3 Activities',
        caricon: "fa-solid fa-car",
        carstat: "1 Transfer",
        category: "Family Pack",
        living: 'Bangalore, India',
        going:"/bangalore"
    },
        
    {
        id: 1,
        photo: "img/tamil.jpg",
        duration: '6 days, 5 nights',
        price: '30,108',
        name: "Trip to The Land of Temples",
        planeicon: "fa-solid fa-plane",
        planestat: '3 Flights',
        hotelicon: "fa-solid fa-building",
        hotelstat: '4 Hotels',
        personicon: "fa-solid fa-person-walking",
        personstat: '3 Activities',
        caricon: "fa-solid fa-car",
        carstat: "1 Transfer",
        category: "Family Pack",
        living: 'Tamil Nadu, India',
        going:"/tamilNadu"
    },
        
    {
        id: 1,
        photo: "img/uk.jpg",
        duration: '6 days, 5 nights',
        price: '26,134',
        name: "Explore the Lands of Uttarakhand",
        planeicon: "fa-solid fa-plane-slash",
        planestat: '0 Flight',
        hotelicon: "fa-solid fa-building",
        hotelstat: '3 Hotels',
        personicon: "fa-solid fa-person-walking",
        personstat: '3 Activities',
        caricon: "fa-solid fa-car",
        carstat: "2 Transfers",
        category: "Adventure Pack",
        living: 'Uttarakhand, India',
        going:"/uttarakhand"
    },
        
    {
        id: 1,
        photo: "img/kashmir.jpg",
        duration: '5 days, 4 nights',
        price: '16,118',
        name: "Take an Adventure in Kashmir",
        planeicon: "fa-solid fa-plane-slash",
        planestat: '0 Flight',
        hotelicon: "fa-solid fa-building",
        hotelstat: '3 Hotels',
        personicon: "fa-solid fa-person-walking",
        personstat: '3 Activities',
        caricon: "fa-solid fa-car",
        carstat: "1 Transfer",
        category: "Adventure Pack",
        living: 'jammu and Kashmir, India',
        going:"/kashmir"
    },
        
    {
        id: 1,
        photo: "img/arunachal.jpg",
        duration: '7 days, 6 nights',
        price: '26,134',
        name: "Visit the Land of rising Sun",
        planeicon: "fa-solid fa-plane-slash",
        planestat: '0 Flight',
        hotelicon: "fa-solid fa-building",
        hotelstat: '3 Hotels',
        personicon: "fa-solid fa-person-walking",
        personstat: '5 Activities',
        caricon: "fa-solid fa-car",
        carstat: "2 Transfers",
        category: "Solo Pack",
        living: 'Arunachal Pradesh, India',
        going:"/arunachalpradesh"
    }
]

export default Dom;