const Inter = [
    {
        id: 1,
        photo: "img/card-img-3.jpg",
        duration: '7 days, 6nights',
        price: '49,999',
        name: 'Explore beautiful beaches of Bali',
        planeicon: "fa-solid fa-plane",
        planestat: '3 Flights',
        hotelicon: "fa-solid fa-building",
        hotelstat: '1 Hotel',
        personicon: "fa-solid fa-person-walking",
        personstat: '1 Activity',
        caricon: "fa-solid fa-car",
        carstat: "0 Transfer",
        category: "Family Pack",
        living: 'Bali Indonesia',
        going:"/bali"
    },
    
    {
        id: 1,
        photo: "img/card-img-4.jpg",
        duration: '10 days, 9nights',
        price: '4,95,825',
        name: 'Japanese extravaganza',
        planeicon: "fa-solid fa-plane",
        planestat: '6 Flights',
        hotelicon: "fa-solid fa-building",
        hotelstat: '2 Hotels',
        personicon: "fa-solid fa-person-walking",
        personstat: '0 Activity',
        caricon: "fa-solid fa-car",
        carstat: "0 Transfer",
        category: "Solo Pack",
        living: 'Tokyo & Osaka, Japan',
        going:"/japan"
    },
        
    {
        id: 1,
        photo: "img/card-img-9.jpg",
        duration: '5 days, 4 nights',
        price: '4,95,825',
        name: 'Experience the luxurious life in Maldives',
        planeicon: "fa-solid fa-plane",
        planestat: '3 Flights',
        hotelicon: "fa-solid fa-building",
        hotelstat: '1 Hotel',
        personicon: "fa-solid fa-person-walking",
        personstat: '3 Activities',
        caricon: "fa-solid fa-car",
        carstat: "0 Transfer",
        category: "Couples Pack",
        living: 'Maldives',
        going:"/maldives"
    },
        
    {
        id: 1,
        photo: "img/card-img-10.jpg",
        duration: '5 days, 4 nights',
        price: '45,999',
        name: 'A short break to Sri Lanka',
        planeicon: "fa-solid fa-plane",
        planestat: '2 Flights',
        hotelicon: "fa-solid fa-building",
        hotelstat: '2 Hotels',
        personicon: "fa-solid fa-person-walking",
        personstat: '2 Activities',
        caricon: "fa-solid fa-car",
        carstat: "1 Transfer",
        category: "Family Pack",
        living: 'Colombo, Sri Lanka',
        going:"/colombo"
    },
        
    {
        id: 1,
        photo: "img/card-img-11.jpg",
        duration: '10 days, 9 nights',
        price: '1,99,927',
        name: 'Discover offbeat South Africa',
        planeicon: "fa-solid fa-plane",
        planestat: '3 Flights',
        hotelicon: "fa-solid fa-building",
        hotelstat: '3 Hotels',
        personicon: "fa-solid fa-person-walking",
        personstat: '5 Activities',
        caricon: "fa-solid fa-car",
        carstat: "0 Transfer",
        category: "Adventure Pack",
        living: 'South Africa',
        going:"/southafrica"
    },
        
    {
        id: 1,
        photo: "img/card-img-12.jpg",
        duration: '4 days, 3 nights',
        price: '49,629',
        name: "Explore the world's tallest buildings in Dubai",
        planeicon: "fa-solid fa-plane",
        planestat: '7 Flights',
        hotelicon: "fa-solid fa-building",
        hotelstat: '1 Hotel',
        personicon: "fa-solid fa-person-walking",
        personstat: '0 Activity',
        caricon: "fa-solid fa-car",
        carstat: "0 Transfer",
        category: "Family Pack",
        living: 'Dubai, UAE',
        going:"/dubai"
    },
        
    {
        id: 1,
        photo: "img/honu.jpg",
        duration: '7 days, 6 nights',
        price: '75,569',
        name: "Take a Swim in Honululu",
        planeicon: "fa-solid fa-plane",
        planestat: '4 Flights',
        hotelicon: "fa-solid fa-building",
        hotelstat: '1 Hotel',
        personicon: "fa-solid fa-person-walking",
        personstat: '3 Activities',
        caricon: "fa-solid fa-car",
        carstat: "0 Transfer",
        category: "Couples Pack",
        living: 'Honululu, Hawaii',
        going:"/hawaii"
    },
        
    {
        id: 1,
        photo: "img/capa.jpg",
        duration: '10 days, 9 nights',
        price: '1,25,028',
        name: "Let your Dreams take Flight in Cappadocia",
        planeicon: "fa-solid fa-plane",
        planestat: '3 Flights',
        hotelicon: "fa-solid fa-building",
        hotelstat: '6 Hotels',
        personicon: "fa-solid fa-person-walking",
        personstat: '0 Activity',
        caricon: "fa-solid fa-car",
        carstat: "0 Transfer",
        category: "Adventure Pack",
        living: 'Cappadocia, Turkey',
        going:"/turkey"
    },
        
    {
        id: 1,
        photo: "img/nepal.jpg",
        duration: '6 days, 5 nights',
        price: '29,078',
        name: "Get a Fresh Perspective in the Mountains",
        planeicon: "fa-solid fa-plane",
        planestat: '2 Flights',
        hotelicon: "fa-solid fa-building",
        hotelstat: '2 Hotels',
        personicon: "fa-solid fa-person-walking",
        personstat: '0 Activity',
        caricon: "fa-solid fa-car",
        carstat: "0 Transfer",
        category: "Adventure Pack",
        living: 'Kathmandu, Nepal',
        going:"/nepal"
    },
        
    {
        id: 1,
        photo: "img/australia.jpg",
        duration: '7 days, 6 nights',
        price: '1,77,100',
        name: "A trip to Australia is always emu-sing",
        planeicon: "fa-solid fa-plane",
        planestat: '3 Flights',
        hotelicon: "fa-solid fa-building",
        hotelstat: '2 Hotels',
        personicon: "fa-solid fa-person-walking",
        personstat: '5 Activities',
        caricon: "fa-solid fa-car",
        carstat: "0 Transfer",
        category: "Family Pack",
        living: 'Sydney, Australia',
        going:"/australia"
    },
        
    {
        id: 1,
        photo: "img/singapore.jpg",
        duration: '6 days, 5 nights',
        price: '60,907',
        name: "Create Cherished memories in the Lion City",
        planeicon: "fa-solid fa-plane",
        planestat: '3 Flights',
        hotelicon: "fa-solid fa-building",
        hotelstat: '2 Hotels',
        personicon: "fa-solid fa-person-walking",
        personstat: '4 Activities',
        caricon: "fa-solid fa-car",
        carstat: "3 Transfers",
        category: "Couples Pack",
        living: 'Singapore',
        going:"/singapore"
    },
        
    {
        id: 1,
        photo: "img/mauritius.jpg",
        duration: '7 days, 6 nights',
        price: '98,882',
        name: "Find your Happy place in Mauritius",
        planeicon: "fa-solid fa-plane",
        planestat: '2 Flights',
        hotelicon: "fa-solid fa-building",
        hotelstat: '2 Hotels',
        personicon: "fa-solid fa-person-walking",
        personstat: '3 Activities',
        caricon: "fa-solid fa-car",
        carstat: "3 Transfers",
        category: "Family Pack",
        living: 'Mauritius, South-east Africa',
        going:"/mauritius"
    },
        
    {
        id: 1,
        photo: "img/malaysia.jpg",
        duration: '6 days, 5 nights',
        price: '64,857',
        name: "Discover Hidden Gems in Kuala Lumpur",
        planeicon: "fa-solid fa-plane",
        planestat: '2 Flights',
        hotelicon: "fa-solid fa-building",
        hotelstat: '2 Hotels',
        personicon: "fa-solid fa-person-walking",
        personstat: '4 Activities',
        caricon: "fa-solid fa-car",
        carstat: "4 Transfers",
        category: "Solo Pack",
        living: 'Kuala Lumpur, Malaysia',
        going:"/malaysia"
    },
        
    {
        id: 1,
        photo: "img/santorini.jpg",
        duration: '6 days, 5 nights',
        price: '1,62,014',
        name: "This island just ouzos with charm",
        planeicon: "fa-solid fa-plane",
        planestat: '4 Flights',
        hotelicon: "fa-solid fa-building",
        hotelstat: '2 Hotels',
        personicon: "fa-solid fa-person-walking",
        personstat: '7 Activities',
        caricon: "fa-solid fa-car",
        carstat: "0 Transfer",
        category: "Couples Pack",
        living: 'Santorini, Greek',
        going:"/santorini"
    },
        
    {
        id: 1,
        photo: "img/amsterdam.jpg",
        duration: '9 days, 8 nights',
        price: '1,96,822',
        name: "Bike your way through Amsterdam",
        planeicon: "fa-solid fa-plane",
        planestat: '5 Flights',
        hotelicon: "fa-solid fa-building",
        hotelstat: '3 Hotels',
        personicon: "fa-solid fa-person-walking",
        personstat: '0 Activity',
        caricon: "fa-solid fa-car",
        carstat: "0 Transfer",
        category: "Adventure Pack",
        living: 'Amsterdam, Netherlands',
        going:"/amsterdam"
    }
]

export default Inter;